---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: piano-deployment
spec:
  replicas: 2  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: piano
  template:
    metadata:
      labels:
        app: piano
    spec:
      containers:
      - name: piano
        image: ziyadtarek99/piano-project:1.0
        #imagePullPolicy: Always
        ports:
        - containerPort: 80
