apiVersion: v1
kind: Service
metadata:
  name: piano-service
spec:
  selector:
    app: piano
  type: NodePort
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080